# Generated by Django 3.1.4 on 2021-02-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
