# Generated by Django 3.1.4 on 2021-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210209_1636'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ManyToManyField(related_name='basket', related_query_name='basket', to='products.Product', verbose_name='product'),
        ),
    ]
