# Generated by Django 3.1.4 on 2021-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_basketitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
    ]
