# Generated by Django 3.1.4 on 2021-02-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210209_1636'),
        ('orders', '0003_basketitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basket', related_query_name='basket', to='products.product', verbose_name='product'),
        ),
    ]
