# Generated by Django 3.1.4 on 2021-02-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210215_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=1500, verbose_name='description'),
        ),
    ]
