# Generated by Django 3.1.4 on 2021-02-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210209_1636'),
        ('orders', '0005_auto_20210216_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='order_item', related_query_name='order_item', to='products.product', verbose_name='product'),
        ),
    ]
