# Generated by Django 3.1.4 on 2021-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210209_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
